apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollout-bluegreen
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ShahadSha/BG-with-ArgoRollouts-and-Istio.git
    targetRevision: HEAD
    path: test
  destination: 
    server: https://kubernetes.default.svc
    namespace: springboot

  syncPolicy:
    # syncOptions:
    # - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
