apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollout-bluegreen
  annotations:
    sidecar.istio.io/inject: 'true'
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ShahadSha/BG-with-ArgoRollouts-and-Istio.git
    targetRevision: HEAD
    path: springboot
  destination: 
    server: https://kubernetes.default.svc
    namespace: springboot

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
