apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollout-bluegreen
  namespace: argocd
spec:
  project: default
  source:
    chart: springboot
    targetRevision: 1.16.0
    repoURL: https://github.com/ShahadSha/BG-with-ArgoRollouts-and-Istio.git
    # targetRevision: HEAD
    path: springboot/templates
  destination: 
    server: https://kubernetes.default.svc
    namespace: springboot

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
